### ISSUE TITLE
Font render differs between math and math-tex

### ISSUE THREAD

**Issue by duxswhatdux** [gtg922r/obsidian-numerals#74]
Hi. Thanks for this plugging I really like, simplistic for everyday use.

There are time I might use both styles, noticing the font rendering in math-Tex is Roman numerals when using IOS. I haven’t tried this on desktop yet. 

Are there plans to harmonize font rendering between the styles, or is this done by intention?
![IMG_5435](https://github.com/gtg922r/obsidian-numerals/assets/45373146/4c876502-a901-4db7-88d8-f0df9eb0c8f6)

**Comment by gtg922r** [comment]
The font difference is intentional. 

The `-tex` block is rendered by Obsidian's built-in mathjax renderer, which styles the text with its own font-family.  This is intentional for those who like tex styling and fonts. 

The `-plaint` style uses whatever the default obsidian monospace font is. 

You can use a css snippet to change the font for numerals `-tex` if you like. 
```css
.numerals-tex .MJX-TEX {
    font-family: var(--numerals-font);
}
```

Or you can use a css snippet or the style settings plugin to change the font for `-plain` and `-highlight` modes. 

```css
.numerals-block {
    --numerals-font: MJXZERO, MJXTEX;
}
```

Note: I haven't tested either of these extensively so your mileage may vary.
